### ISSUE TITLE
TA Review - Standards

### ISSUE THREAD

**Issue by John-Popovici** [John-Popovici/duel-of-the-eights#59]
**Artifact Under Review**
SRS

**Rubric Section and Grade**
Feedback for LO_Standards - 1/3

**Description of Issue**
Absent from doc; only reason why this isn't a zero is because it is hard to come up with in the context of a game. One aspect to think about is in multiplayer PvP matches - are there any standards that should be taken into account in this situation?

**Comment by nigelmoses32** [comment]
Added sections Standards and Compliance Roadmap to SRS
