### ISSUE TITLE
TA Review - Link Changes to Requirements

### ISSUE THREAD

**Issue by John-Popovici** [John-Popovici/duel-of-the-eights#67]
**Artifact Under Review**
SRS

**Rubric Section and Grade**
Basis for Design - 2/3

**Description of Issue**
While likely and unlikely changes were given, they should be linked to requirements (at least for unlikely changes which the rubric item states in "Exceeds").

**Comment by nigelmoses32** [comment]
In commit: 5bd2f8211086a0c68ff540ad84b25df5361ff0ed added brief text in the justification for each unlikely change to reference the relevant requirements
